### ISSUE TITLE
PMT Error : monitor loading file

### ISSUE THREAD

**Issue by GautierRtlc** [NXPmicro/pmt#1]
Hi, 

I'm actually working with PMT, I saved .csv and .pmt file in the way to use it later by opening it thank to the commande below :
`python3 main.py monitor -m gui -l path/to/file/file.csv`

On the terminal, I have this : 
```
Reading path/to/file/file.csv
Please enter valid file to load
```
**UpDate : It's only working when I put my files into the example repertory. Can I modify that ?**

Thank for consideration !
Gautier

**Comment by MathisDeroo** [comment]
Hi @GautierRtlc,

The command you have used is the good one.
Can you provide a concrete example please ?

I've done some tests on my side and it works well whatever the location of the csv file.
While running PMT, I saved a capture called test.csv under Video directory.

Traces are:
`Saved data in file /home/nxf/Videos/test.csv`
Then I can run the command `python3 main.py monitor -m gui -l /home/nxf/Videos/test.csv`

Thanks,
Mathis

**Comment by GautierRtlc** [comment]
There is an example file 'pmt_example.csv'.
When this file is in : `~/stage/pmt/pmt-master/examples/pmt_example.csv`, it's working perfectly, the gui opens and I have the graphs etc

If I copy/paste the same file in another way like this one : `~/stage/pmt/data_saved/pmt_example.csv`, I have this error :
```
Reading ../data_saved/pmt_example.csv file...
Please enter valid file to load
```
The GUI opens but there is nothing.

It's the same for a file that I saved by myself using PMT or bcu.

Thanks,
Gautier

**Comment by MathisDeroo** [comment]
Which OS are you using ?
When the error occurs the GUI is an empty window ?

Thanks,
Mathis

**Comment by GautierRtlc** [comment]
I'm using "Ubuntu 20.04.4 LTS" thank to a VirtualMachine on Windows 10.
The GUI is not empty, it's look like normal without any datas.
![Screen](https://user-images.githubusercontent.com/83223077/156742076-cff03b20-0514-4561-b08e-010602a93f5b.png)

Gautier

**Comment by MathisDeroo** [comment]
Thanks for the information.
To confirm that the issue is identified, can you please specify the full path of the file to load ?
In the directory file, run `pwd` to access the path to specify in command line.

Thanks,
Mathis

**Comment by GautierRtlc** [comment]
Here it is : `/home/aph01/stage/pmt/data_saved`

Thanks,
Gautier

**Comment by MathisDeroo** [comment]
Does it work while specifying this path instead of `../data_saved/pmt_example.csv` ?

Mathis

**Comment by GautierRtlc** [comment]
Yes it is working !

Thanks,
Gautier

**Comment by MathisDeroo** [comment]
Good new ! So the issue is identified.
I will update the method to manage the file to load in a next release.
In the meantime, you can specify the **full path** of the file to load in GUI.

Thanks,
Mathis

**Comment by GautierRtlc** [comment]
Well thank you for your help ! I appreciate it !
Good luck to fix that !

Thank you again,
Gautier

**Comment by MathisDeroo** [comment]
Hi @GautierRtlc,

Issue is fixed in PMT_V2.5, commit `053e246cca9e99df7da6c20a9e32b827cf7a2af9`.

Thanks,
Mathis
